Imports System.IO
Public Class ConfigurationFile

    Private Const _operatorCFG As String = " = "
    Private Const _extensionCFG As String = ".cfg"
    Private Const _subTitleCFG As String = " configuration file"

    Private Structure CommentCFG
        Public Const generate As String = "Generated by Kitserver 6 Settings"
        Public Const line As String = "###################################"
    End Structure

    Protected ReadOnly Property OperatorCFG
        Get
            Return _operatorCFG
        End Get
    End Property

    Protected ReadOnly Property ExtensionCFG
        Get
            Return _extensionCFG
        End Get
    End Property

    Protected ReadOnly Property SubTitleCFG
        Get
            Return _subTitleCFG
        End Get
    End Property

    Public Sub New()

    End Sub

    Public Function ExistCFG(ByVal fileName As String) As Boolean

        If File.Exists(fileName) Then
            Return True
        Else
            Return False
        End If

    End Function

    Public Function DeleteCFG(ByVal fileName As String) As Boolean

        Try
            File.Delete(fileName)
            Return True
        Catch ex As Exception
            Return False
        End Try

    End Function

    Public Function WriteCFG(ByVal fileName As String, ByVal titleText As String, ByVal dataText As String) As Boolean

        Try
            Using sw As StreamWriter = File.CreateText(fileName)
                sw.WriteLine("# " & titleText)
                sw.WriteLine("# Generated by Kitserver 6 Settings")
                sw.WriteLine("###################################")
                sw.WriteLine("")
                sw.WriteLine(dataText)
                sw.Close()
            End Using
            Return True
        Catch ex As Exception
            Return False
        End Try

    End Function

    Public Function ReadCFG(ByVal fileName As String, ByVal keyValue As String, Optional ByVal startLine As Boolean = True)
        Dim line As String
        Dim equally As String = Me.OperatorCFG

        Try
            Using sr As StreamReader = New StreamReader(fileName)
                Do
                    line = sr.ReadLine
                    If line.Contains(keyValue) Then
                        If startLine Then
                            If line.StartsWith(keyValue.Substring(0, 1)) Then
                                line = line.Replace(keyValue, "").Replace(equally.Replace(" ", ""), "").Replace(" ", "")
                                Return line
                            End If
                        Else
                            line = line.Replace(keyValue, "").Replace(equally.Replace(" ", ""), "").Replace("#", "").Replace(" ", "")
                            Return line
                        End If
                    End If
                Loop Until sr.EndOfStream
            End Using
            Return Nothing
        Catch ex As Exception
            Return Nothing
        End Try

    End Function


    Public Function ConvertEnable(ByVal valueInput As Boolean) As Integer

        If valueInput Then
            Return 1
        Else
            Return 0
        End If

    End Function

    Public Function ConvertValue(ByVal valueInput As String) As Boolean

        If valueInput = "0" Then
            Return False
        Else
            Return True
        End If

    End Function

End Class
